[edge]
# Replace with your real host(s). Add one line per server.
# host-or-ip ansible_user=USER ansible_ssh_pass=PASSWORD ansible_become_pass=PASSWORD
192.168.2.140 ansible_user=devops ansible_ssh_pass='DevOps@2022#' ansible_become_pass='DevOps@2022#'
192.168.2.128 ansible_user=devops ansible_ssh_pass='DevOps@2022#' ansible_become_pass='DevOps@2022#'
192.168.2.190 ansible_user=devops ansible_ssh_pass='DevOps@2022#' ansible_become_pass='DevOps@2022#'
192.168.2.126 ansible_user=devops ansible_ssh_pass='DevOps@2022#' ansible_become_pass='DevOps@2022#'
192.168.2.127 ansible_user=devops ansible_ssh_pass='DevOps@2022#' ansible_become_pass='DevOps@2022#'
# Add more hosts below, one per line:
# 192.168.1.11 ansible_user=devops ansible_ssh_pass='DevOps@2022#' ansible_become_pass='DevOps@2022#'

[edge:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
